// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZAZFRYc-j-2Fc2n70wowKYH6kj7NLoY',
    appId: '1:1017976905493:web:1a514b04bdd79170cf931c',
    messagingSenderId: '1017976905493',
    projectId: 'nienluanchuyennganh-32bd0',
    authDomain: 'nienluanchuyennganh-32bd0.firebaseapp.com',
    storageBucket: 'nienluanchuyennganh-32bd0.firebasestorage.app',
    measurementId: 'G-JVXFR6Y2H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJOUTFHmR2i4vucau3B2_K2VLkDZ1nVk',
    appId: '1:1017976905493:android:724b9c239042ec7ccf931c',
    messagingSenderId: '1017976905493',
    projectId: 'nienluanchuyennganh-32bd0',
    storageBucket: 'nienluanchuyennganh-32bd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jg_PF9917vdZK2tVQkzAWoTQlI6xr5g',
    appId: '1:1017976905493:ios:eb4cddfd5ea735bbcf931c',
    messagingSenderId: '1017976905493',
    projectId: 'nienluanchuyennganh-32bd0',
    storageBucket: 'nienluanchuyennganh-32bd0.firebasestorage.app',
    iosBundleId: 'com.example.hocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jg_PF9917vdZK2tVQkzAWoTQlI6xr5g',
    appId: '1:1017976905493:ios:eb4cddfd5ea735bbcf931c',
    messagingSenderId: '1017976905493',
    projectId: 'nienluanchuyennganh-32bd0',
    storageBucket: 'nienluanchuyennganh-32bd0.firebasestorage.app',
    iosBundleId: 'com.example.hocado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjZAZFRYc-j-2Fc2n70wowKYH6kj7NLoY',
    appId: '1:1017976905493:web:80003baac0e317e6cf931c',
    messagingSenderId: '1017976905493',
    projectId: 'nienluanchuyennganh-32bd0',
    authDomain: 'nienluanchuyennganh-32bd0.firebaseapp.com',
    storageBucket: 'nienluanchuyennganh-32bd0.firebasestorage.app',
    measurementId: 'G-GBX6ES7T2G',
  );
}
